# Generated by Django 4.1 on 2022-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modifiedDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de modifiación')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
