# Generated by Django 4.1 on 2022-09-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'db_table': 'action_types',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('targetId', models.IntegerField(blank=True, null=True, verbose_name='Id del objeto')),
                ('url', models.CharField(max_length=500, verbose_name='Url')),
                ('ipUser', models.CharField(max_length=70, verbose_name='IP de usuario')),
                ('value', models.CharField(max_length=70, verbose_name='Valor')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actionType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logs.actiontype')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
